sonar.projectKey=23deFevereiro_API_5_SEM_FRONT
sonar.organization=23defevereiro-1

sonar.exclusions=**/.github/workflows/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  src/main.ts,\
  src/env.d.ts,\
  src/typed-router.d.ts,\
  src/plugins/**,\
  src/router/**,\
  src/styles/**,\
  src/assets/**,\
  src/stores/app.ts,\
  src/**/*.spec.ts
