sonar.projectKey=23deFevereiro_API_5_SEM_FRONT
sonar.organization=23defevereiro-1

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  src/main.ts,\
  src/plugins/**,\
  src/router/**,\
  src/typed-router.d.ts